sudo: required
services:
  - docker

language: go
go:
- '1.10'
before_install:
  - curl -L -o /tmp/dep-linux-amd64 https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && install -m 0755 /tmp/dep-linux-amd64 $GOPATH/bin/dep
install: dep ensure -vendor-only
script: go test -v ./...

before_deploy:
  - docker build -t qmsk-e2_build build/
  - install -d -m 0777 dist
  - |
    docker run --rm \
    -v $PWD/dist:/dist \
    -v $PWD:/src \
    -e SRC=/src \
    -e DIST=/dist \
      qmsk-e2_build
deploy:
  skip_cleanup: true
  on:
    tags: true
    go: '1.10'
  provider: releases
  api_key:
    secure: "ChMW+s/WvS+qdYhGdZoom5QqtFMjAXu1oHW/KyGcbUX1GBmf+mXk2Av22wr7lLWtZKzh6gpgfiPHxGNvQuctnZncGchSDqIbS2FyW+33vha4drWs8Z6RgWPcYYvYcDEO5rj+UDGgc+ARVCQtpLUMmOSfOhkLq574Cu2O0MFw/yfD5046pVsynTt3kgdWQnTxP78juw0LePafNswjTMXuoIGt5B46mrKCsVdxDh3ufP5dfuthe987QgXr6WkMFf6Chv/K/65Al89hsULgmqtDRtqmeMebLxOEXMYg7w54N3NDWe9baAlNQm57w5zSsvEnji3gWfub/5i6PMMDaixSCdUv5luYYGFDv4JuarfVuws5sYy5+2cGSxLE75u67akRRjU5ILgKEokA1yk9Soarzv1cQxefsOxH/KaW/gormu/pVX2hsdCLjA3cv8QFBIiqt6mcXLcD5LCBM+SrVslAOUBspmy7lsEC0HiHrHnVDhdszE1FPQLRL5GyGr3cxcBBXRLoh5jrt+dPRYgtdPVkDjJp0sEIC9ICYYuJorBNpgv6coTzqFXW7j1ItjniCxrJTwp8K4p3nI/t0QCFZO7SqR3BD9m//jvBu+QjBtNPs9re+ZUetI2HJsoYjLYlyLzYt+J9Hs94g469MFzDrd+qAEB6caEZLkRfNzMnqS0mVP4="
  file_glob: true
  file:
    - dist/SHA256SUM
    - dist/*.tar.gz
