sudo: required
services:
  - docker

language: go
go:
- '1.6'
- '1.9'
install: go get -v -t -d ./...
script: go test -v ./...

before_deploy:
  - docker build -t qmsk-e2_build build/
  - |
    docker run \
    -v $PWD/dist:/dist \
    -v $PWD:/src \
    -e SRC=/src \
    -e DIST=/dist \
      qmsk-e2_build
deploy:
  skip_cleanup: true
  on:
    tags: true
    go: '1.6'
  provider: releases
  api_key:
    secure:
  file_glob: true
  file: build/*.tar.gz
