# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/kidoman/embd"
  source = "github.com/SpComb/embd"
  branch = "digitalpin-exported"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  name = "github.com/lucasb-eyer/go-colorful"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/tarm/serial"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

# golang.org/x/sys/unix is broken on Go 1.6 as of https://github.com/golang/sys/commit/e072cadbbdc8dd3d3ffa82b8b4b9304c261d9311
#
# https://github.com/qmsk/e2/issues/33
# https://github.com/golang/go/issues/26576
[[override]]
  name = "golang.org/x/sys"
  revision = "ac767d655b"

[prune]
  go-tests = true
  unused-packages = true
